### ISSUE TITLE
Incorrect password causes IP ban on Passthepopcorn

### ISSUE THREAD

**Issue by nervling** [CouchPotato/CouchPotatoServer#2232] opened 2013-09-23 14:39 UTC
Could we make couchpotato quit attempting to log into passthepopcorn on incorrect password until the user does something? I changed my password on passthepopcorn and didn't think to change it in couchpotato (figured it was an api key) so I got IP banned twice before I figured out why.

**Comment by LovesToSp00ge** [comment] 2015-05-19 12:51
this happened to me also, this thing got me IP banned, I know its cause I forgot to change password but I figured it would just stop trying to login after it failed that many time :/ please fix this flaw

**Comment by Amelandbor** [comment] 2015-05-20 07:59
Would it be as simple as something like this:

```
    def loginSuccess(self, output):
        try:
            return json.loads(output).get('Result', '').lower() == 'ok'
        except:
        	loginErrors ++
        	if loginErrors == 3:
        		self.conf('enabled') = False
        		return False
            else:
            	return False

**Comment by Amelandbor** [comment] 2015-05-29 08:44
Anyone any thoughts if this is the way to go?
Or do I need to use a global variable for this?

**Comment by jkaberg** [comment] 2015-05-29 08:47
@Amelandbor I like your solution, but this should be more generic (for all providers). And the user should be notified when an provider is deactivated

Ultimately it's up to @RuudBurger

**Comment by kyleshrader** [comment] 2015-08-06 08:49
Agreed. There is no point in retrying known incorrect credentials. Ultimately, CouchPotato is meant to interface with these providers. Is there anything we can do to help, @RuudBurger?

**Comment by Groxxxy** [comment] 2015-08-29 03:45
@RuudBurger, can you please take care of this issue. This issue disables users and is the most frequent problem run into by the PTP staff and support team. It is a headache and a significant expenditure of time for the user and the staff member to be both available across time zones to deal with this.

Please @RuudBurger.

**Comment by RuudBurger** [comment] 2015-08-29 16:17
Two things about this, my account got blocked multiple times. Hard for me to fix it if I can't use the services. Add a proper API with API key seems the way to go. As you can limit it properly, see requests on a per-app basis and I don't need to scrape existing calls to search for movies.

**Comment by Lemon-Chello** [comment] 2015-08-30 18:23
@RuudBurger With all due respect, this issue would be completely solved if your code simply conformed to globally accepted REST behaviors.  It'd be quicker and cleaner than trying to get external parties to write an entirely new api to support your project.

If a server responds with a 401, or a 403 then it is universally understood that you should not continue sending the same unaltered request over and over again.  It's explicitly stated in the RFC:  http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

```
10.4.4 403 Forbidden

The server understood the request, but is refusing to fulfill it. Authorization will not help and __the request SHOULD NOT be repeated.__

10.4.2 401 Unauthorized

...If the request already included Authorization credentials, then __the 401 response indicates that authorization has been refused for those credentials.___ ...
```

The problem is that CP does not respect this behavior, and instead continues to bombard the server with invalid requests.  This is contrary to normal web standards.

Honestly you could go a step further and on https://github.com/RuudBurger/CouchPotatoServer/blob/69825f9dbdfc42d5e6fcebd89828e21ff36330fa/couchpotato/core/media/_base/providers/torrent/passthepopcorn.py#L178 disable the plugin if the response is not a 408/504 timeout && result != ok.   Since at that point you're pretty much guaranteed that your auth attempt is failing.

**Comment by RuudBurger** [comment] 2015-08-30 21:08
I didn't write the provider for PTP, but I will have a look once I get an account again.

**Comment by Lemon-Chello** [comment] 2015-08-30 22:09
I know they have a disabled channel on their irc server, perhaps try there?

Though the http status codes will be the same regardless, no?

**Comment by Groxxxy** [comment] 2015-08-31 01:00
Hello again Mr. Burger,

Can I first start with informing you that PTP has a strict one account per lifetime policy. If you would like to contribute as well as take advantage of the largest movie repository on the planet can I please ask that you have your previous account re-enabled by going to the IRC server at irc.passthepopcorn.me and asking to be enabled in the #ptp-disabled channel.

It is ironic that now you must face a long waiting time to speak with staff to be enabled again as a result of CouchPotato effectively disabling you just like it has thousands of other people. People who contributed to the site and who many we have lost because some do not have the patience to wait in our support channel.

A developer told me that implementing @Amelandbor 's above solution would be enough to solve this issue.

If you would like to test that it works after implementing it please @RuudBurger stop by our support channel to be allowed access again.

Kind regards.

**Comment by RuudBurger** [comment] 2015-08-31 09:20
@Groxxxy Added myself to the queue ;)

**Comment by Groxxxy** [comment] 2015-09-09 00:49
How has progress been @RuudBurger ?

Staff inform me they can't tell if they spoke with you in the #ptp-disabled channel. If you inform them that you are the developer, PTP can work better with you to resolve this issue.

**Comment by RuudBurger** [comment] 2015-09-09 09:21
Twice I've been in the queue for 8+ hours. My username is `Crashdummy12` so if you can pass it though and they can reset it, that would be great.

**Comment by Groxxxy** [comment] 2015-09-09 13:26
You can only be enabled if you're there in the channel. It's normal to wait much longer than 8 hours.

**Comment by RuudBurger** [comment] 2015-09-09 15:11
Then no, no progress...

**Comment by Groxxxy** [comment] 2015-09-10 23:12
A user one hour ago in the support channel:
>hello there, during my NAS upgrade I reinstalled Couchpotato and for some reason it started logging in without credentials causing a IP block. I turned off PTP in CP but I'm still blocked. Is there anything that can be done about that?

**Comment by mano3m** [comment] 2015-09-12 16:23
@Groxxxy as you can see RuudBurger is willing to help. It might help the situation if you give him access to the site without going through the 'normal' wait of a few days in a channel...

**Comment by Groxxxy** [comment] 2015-09-14 02:32
I am being proactive but I'm not the management of the site, which if you could know is not a normal site. Besides, RuudBurger will need to log in within an hour of being enabled otherwise risk being inactivity disabled. They need to be communicated with to know when to do that.

I don't actually know if RuudBurger is disabled. Maybe all they have to do is log in since the site blocks IPs if the login is wrong for only six hours.

**Comment by Lemon-Chello** [comment] 2015-09-21 04:23
@RuudBurger Staff are generally available in the afternoon EST.  Voltaire said you can send him a pm and identify yourself and he'll bump you to the front of the line.

@mano3m I'm a bit confused why he needs to get his account re-enabled at all though in order to trouble shoot this?  The issue is with unsuccessful logins.  It could be debugged without an account at all.

The solution posed by @Amelandbor https://github.com/RuudBurger/CouchPotatoServer/issues/2232#issuecomment-103800804 would work just fine as is.  If preferable we could get someone to submit it as a PR...but I'm not sure I understand the point of jumping through such hoops.

**Comment by RuudBurger** [comment] 2015-09-22 10:27
Merged the PR.

**Closed** 2016-04-25 21:00 UTC
Labels: 4 - Feature
